language: cpp
branches:
  only:
  - master
matrix:
  include:
  - os: osx
    compiler: clang
    env:
    - FILE=tikzit-osx.dmg
    - QTVER=511
    - DEPLOY_TIKZIT=1
addons:
  homebrew:
    brewfile: true
script:
- qmake -v
- qmake -r
- make
- '(chmod +x deploy-osx.sh && ./deploy-osx.sh && mv tikzit.dmg $FILE)'
- python scripts/gh-push.py $FILE
notifications:
  email: false
