#############################################################################
# Makefile for building: tikzit.app/Contents/MacOS/tikzit
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  tikzit.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile tikzit.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Isrc/gui -Isrc/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -F/usr/local/Cellar/qt5/5.7.1_1/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = tikzit1.0.0
DISTDIR = /Users/alek/git/tikzit/tikzit/.tmp/tikzit1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt5/5.7.1_1/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/gui/mainwindow.cpp \
		src/gui/toolpalette.cpp \
		src/gui/tikzscene.cpp \
		src/data/graph.cpp \
		src/data/node.cpp \
		src/data/edge.cpp \
		src/data/tikzgraphassembler.cpp \
		src/data/graphelementdata.cpp \
		src/data/graphelementproperty.cpp \
		src/gui/propertypalette.cpp \
		src/main.cpp src/data/tikzlexer.lexer.cpp \
		src/data/tikzparser.parser.cpp \
		qrc_tikzit.cpp \
		moc_mainwindow.cpp \
		moc_toolpalette.cpp \
		moc_graph.cpp \
		moc_node.cpp \
		moc_edge.cpp \
		moc_tikzgraphassembler.cpp \
		moc_graphelementdata.cpp \
		moc_propertypalette.cpp
OBJECTS       = mainwindow.o \
		toolpalette.o \
		tikzscene.o \
		graph.o \
		node.o \
		edge.o \
		tikzgraphassembler.o \
		graphelementdata.o \
		graphelementproperty.o \
		propertypalette.o \
		main.o \
		tikzlexer.lexer.o \
		tikzparser.parser.o \
		qrc_tikzit.o \
		moc_mainwindow.o \
		moc_toolpalette.o \
		moc_graph.o \
		moc_node.o \
		moc_edge.o \
		moc_tikzgraphassembler.o \
		moc_graphelementdata.o \
		moc_propertypalette.o
DIST          = /usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/default_pre.prf \
		flex.pri \
		bison.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resolve_target.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/testcase.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/lex.prf \
		tikzit.pro src/gui/mainwindow.h \
		src/gui/toolpalette.h \
		src/gui/tikzscene.h \
		src/data/graph.h \
		src/data/node.h \
		src/data/edge.h \
		src/data/tikzgraphassembler.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		src/gui/propertypalette.h \
		src/data/tikzparserdefs.h src/gui/mainwindow.cpp \
		src/gui/toolpalette.cpp \
		src/gui/tikzscene.cpp \
		src/data/graph.cpp \
		src/data/node.cpp \
		src/data/edge.cpp \
		src/data/tikzgraphassembler.cpp \
		src/data/graphelementdata.cpp \
		src/data/graphelementproperty.cpp \
		src/gui/propertypalette.cpp \
		src/main.cpp
QMAKE_TARGET  = tikzit
DESTDIR       = 
TARGET        = tikzit.app/Contents/MacOS/tikzit


first: all
####### Build rules

$(TARGET): src/data/tikzlexer.lexer.cpp src/data/tikzparser.parser.cpp src/data/tikzparser.parser.hpp ui_mainwindow.h ui_propertypalette.h $(OBJECTS)  
	@test -d tikzit.app/Contents/MacOS/ || mkdir -p tikzit.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tikzit.pro /usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/default_pre.prf \
		flex.pri \
		bison.pri \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resolve_target.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/testcase.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/lex.prf \
		tikzit.pro \
		tikzit.qrc \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile tikzit.pro
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/default_pre.prf:
flex.pri:
bison.pri:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resolve_target.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/testcase.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt5/5.7.1_1/mkspecs/features/lex.prf:
tikzit.pro:
tikzit.qrc:
/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile tikzit.pro

qmake_all: FORCE

tikzit.app/Contents/PkgInfo: 
	@test -d tikzit.app/Contents || mkdir -p tikzit.app/Contents
	@$(DEL_FILE) tikzit.app/Contents/PkgInfo
	@echo "APPL????" > tikzit.app/Contents/PkgInfo
tikzit.app/Contents/Resources/empty.lproj: 
	@test -d tikzit.app/Contents/Resources || mkdir -p tikzit.app/Contents/Resources
	@touch tikzit.app/Contents/Resources/empty.lproj
	
tikzit.app/Contents/Info.plist: 
	@test -d tikzit.app/Contents || mkdir -p tikzit.app/Contents
	@$(DEL_FILE) tikzit.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.tikzit,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,tikzit,g" -e "s,@LIBRARY@,tikzit,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang/Info.plist.app >tikzit.app/Contents/Info.plist

all: Makefile \
		tikzit.app/Contents/PkgInfo \
		tikzit.app/Contents/Resources/empty.lproj \
		tikzit.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/data/tikzlexer.l $(DISTDIR)/
	$(COPY_FILE) --parents src/data/tikzparser.y $(DISTDIR)/
	$(COPY_FILE) --parents src/data/tikzparser.y $(DISTDIR)/
	$(COPY_FILE) --parents tikzit.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/gui/mainwindow.h src/gui/toolpalette.h src/gui/tikzscene.h src/data/graph.h src/data/node.h src/data/edge.h src/data/tikzgraphassembler.h src/data/graphelementdata.h src/data/graphelementproperty.h src/gui/propertypalette.h src/data/tikzparserdefs.h $(DISTDIR)/
	$(COPY_FILE) --parents src/gui/mainwindow.cpp src/gui/toolpalette.cpp src/gui/tikzscene.cpp src/data/graph.cpp src/data/node.cpp src/data/edge.cpp src/data/tikzgraphassembler.cpp src/data/graphelementdata.cpp src/data/graphelementproperty.cpp src/gui/propertypalette.cpp src/main.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/gui/mainwindow.ui src/gui/propertypalette.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r tikzit.app
	-$(DEL_FILE) /Users/alek/git/tikzit/tikzit/target_wrapper.sh .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first
	/Users/alek/git/tikzit/tikzit/target_wrapper.sh $(TESTRUNNER) ./$(QMAKE_TARGET).app/Contents/MacOS/$(QMAKE_TARGET) $(TESTARGS)

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

benchmark: first

compiler_flex_make_all: src/data/tikzlexer.lexer.cpp
compiler_flex_clean:
	-$(DEL_FILE) src/data/tikzlexer.lexer.cpp
src/data/tikzlexer.lexer.cpp: src/data/tikzlexer.l
	flex --header-file -o src/data/tikzlexer.lexer.cpp src/data/tikzlexer.l

compiler_bison_make_all: src/data/tikzparser.parser.cpp
compiler_bison_clean:
	-$(DEL_FILE) src/data/tikzparser.parser.cpp
src/data/tikzparser.parser.cpp: src/data/tikzparser.y
	bison -d -o src/data/tikzparser.parser.cpp src/data/tikzparser.y

compiler_bison_header_make_all: src/data/tikzparser.parser.hpp
compiler_bison_header_clean:
	-$(DEL_FILE) src/data/tikzparser.parser.hpp
src/data/tikzparser.parser.hpp: src/data/tikzparser.y
	bison -d -o src/data/tikzparser.parser.cpp src/data/tikzparser.y

compiler_rcc_make_all: qrc_tikzit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_tikzit.cpp
qrc_tikzit.cpp: tikzit.qrc \
		/usr/local/Cellar/qt5/5.7.1_1/bin/rcc \
		images/draw-ellipse.png \
		images/transform-crop-and-resize.png \
		images/draw-path.png \
		images/select-rectangular.png
	/usr/local/Cellar/qt5/5.7.1_1/bin/rcc -name tikzit tikzit.qrc -o qrc_tikzit.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_toolpalette.cpp moc_graph.cpp moc_node.cpp moc_edge.cpp moc_tikzgraphassembler.cpp moc_graphelementdata.cpp moc_propertypalette.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_toolpalette.cpp moc_graph.cpp moc_node.cpp moc_edge.cpp moc_tikzgraphassembler.cpp moc_graphelementdata.cpp moc_propertypalette.cpp
moc_mainwindow.cpp: src/gui/tikzscene.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		src/gui/mainwindow.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/gui/mainwindow.h -o moc_mainwindow.cpp

moc_toolpalette.cpp: /usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QToolBar \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QActionGroup \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qactiongroup.h \
		src/gui/toolpalette.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/gui/toolpalette.h -o moc_toolpalette.cpp

moc_graph.cpp: src/data/node.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QPointF \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qpoint.h \
		src/data/edge.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QMultiHash \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qhash.h \
		src/data/graph.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/data/graph.h -o moc_graph.cpp

moc_node.cpp: src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QPointF \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qpoint.h \
		src/data/node.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/data/node.h -o moc_node.cpp

moc_edge.cpp: src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		src/data/edge.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/data/edge.h -o moc_edge.cpp

moc_tikzgraphassembler.cpp: src/data/node.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QPointF \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qpoint.h \
		src/data/graph.h \
		src/data/edge.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QMultiHash \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qhash.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QHash \
		src/data/tikzgraphassembler.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/data/tikzgraphassembler.h -o moc_tikzgraphassembler.cpp

moc_graphelementdata.cpp: src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		src/data/graphelementdata.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/data/graphelementdata.h -o moc_graphelementdata.cpp

moc_propertypalette.cpp: /usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QDockWidget \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qdockwidget.h \
		src/gui/propertypalette.h \
		/usr/local/Cellar/qt5/5.7.1_1/bin/moc
	/usr/local/Cellar/qt5/5.7.1_1/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.7.1_1/mkspecs/macx-clang -I/Users/alek/git/tikzit/tikzit -I/Users/alek/git/tikzit/tikzit/src -I/Users/alek/git/tikzit/tikzit/src/gui -I/Users/alek/git/tikzit/tikzit/src/data -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt5/5.7.1_1/lib src/gui/propertypalette.h -o moc_propertypalette.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_propertypalette.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_propertypalette.h
ui_mainwindow.h: src/gui/mainwindow.ui \
		/usr/local/Cellar/qt5/5.7.1_1/bin/uic
	/usr/local/Cellar/qt5/5.7.1_1/bin/uic src/gui/mainwindow.ui -o ui_mainwindow.h

ui_propertypalette.h: src/gui/propertypalette.ui \
		/usr/local/Cellar/qt5/5.7.1_1/bin/uic
	/usr/local/Cellar/qt5/5.7.1_1/bin/uic src/gui/propertypalette.ui -o ui_propertypalette.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_flex_clean compiler_bison_clean compiler_bison_header_clean compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: src/gui/mainwindow.cpp src/gui/mainwindow.h \
		src/gui/tikzscene.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		ui_mainwindow.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/gui/mainwindow.cpp

toolpalette.o: src/gui/toolpalette.cpp src/gui/toolpalette.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QToolBar \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QActionGroup \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qactiongroup.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qboxlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolpalette.o src/gui/toolpalette.cpp

tikzscene.o: src/gui/tikzscene.cpp src/gui/tikzscene.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qgraphicsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tikzscene.o src/gui/tikzscene.cpp

graph.o: src/data/graph.cpp src/data/graph.h \
		src/data/node.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QPointF \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qpoint.h \
		src/data/edge.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QMultiHash \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qhash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graph.o src/data/graph.cpp

node.o: src/data/node.cpp src/data/node.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QPointF \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qpoint.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o src/data/node.cpp

edge.o: src/data/edge.cpp src/data/edge.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o src/data/edge.cpp

tikzgraphassembler.o: src/data/tikzgraphassembler.cpp src/data/tikzgraphassembler.h \
		src/data/node.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QPointF \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qpoint.h \
		src/data/graph.h \
		src/data/edge.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QMultiHash \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qhash.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QHash
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tikzgraphassembler.o src/data/tikzgraphassembler.cpp

graphelementdata.o: src/data/graphelementdata.cpp src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphelementdata.o src/data/graphelementdata.cpp

graphelementproperty.o: src/data/graphelementproperty.cpp src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphelementproperty.o src/data/graphelementproperty.cpp

propertypalette.o: src/gui/propertypalette.cpp src/gui/propertypalette.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QDockWidget \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qdockwidget.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		ui_propertypalette.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers/QCloseEvent \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propertypalette.o src/gui/propertypalette.cpp

main.o: src/main.cpp src/gui/mainwindow.h \
		src/gui/tikzscene.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QGraphicsView \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		src/gui/toolpalette.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QToolBar \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QActionGroup \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qactiongroup.h \
		src/gui/propertypalette.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QDockWidget \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qdockwidget.h \
		src/data/graph.h \
		src/data/node.h \
		src/data/graphelementdata.h \
		src/data/graphelementproperty.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QAbstractItemModel \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QModelIndex \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QPointF \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qpoint.h \
		src/data/edge.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/QMultiHash \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtCore.framework/Headers/qhash.h \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt5/5.7.1_1/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

tikzlexer.lexer.o: src/data/tikzlexer.lexer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tikzlexer.lexer.o src/data/tikzlexer.lexer.cpp

tikzparser.parser.o: src/data/tikzparser.parser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tikzparser.parser.o src/data/tikzparser.parser.cpp

qrc_tikzit.o: qrc_tikzit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_tikzit.o qrc_tikzit.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_toolpalette.o: moc_toolpalette.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolpalette.o moc_toolpalette.cpp

moc_graph.o: moc_graph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graph.o moc_graph.cpp

moc_node.o: moc_node.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_node.o moc_node.cpp

moc_edge.o: moc_edge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_edge.o moc_edge.cpp

moc_tikzgraphassembler.o: moc_tikzgraphassembler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tikzgraphassembler.o moc_tikzgraphassembler.cpp

moc_graphelementdata.o: moc_graphelementdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphelementdata.o moc_graphelementdata.cpp

moc_propertypalette.o: moc_propertypalette.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_propertypalette.o moc_propertypalette.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/Cellar/qt5/5.7.1_1/tests/tikzit || mkdir -p $(INSTALL_ROOT)/usr/local/Cellar/qt5/5.7.1_1/tests/tikzit
	$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Cellar/qt5/5.7.1_1/tests/tikzit/tikzit.app
	
	-$(INSTALL_DIR) tikzit.app $(INSTALL_ROOT)/usr/local/Cellar/qt5/5.7.1_1/tests/tikzit/tikzit.app
	-$(STRIP) $(INSTALL_ROOT)/usr/local/Cellar/qt5/5.7.1_1/tests/tikzit/tikzit.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/Cellar/qt5/5.7.1_1/tests/tikzit/tikzit.app
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/Cellar/qt5/5.7.1_1/tests/tikzit/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

