.TH TIKZIT 1
.SH NAME
tikzit \- a simple GUI editor for making graphs and string diagrams
.SH SYNOPSIS
.B tikzit
[\fIfile\fR]
.SH DESCRIPTION
.B tikzit
is a super simple GUI editor for graphs and string diagrams. Its
native file format is a subset of PGF/TikZ, which means TikZiT files
can be included directly in papers typeset using LaTeX.
.SH ARGUMENTS
.TP
.BR file
An optional file name to open.

